"""added bookings cascade deletion in case of a table deletion

Revision ID: 35a0fb5f4843
Revises: 21fc479d1ba8
Create Date: 2024-07-05 17:17:40.339736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a0fb5f4843'
down_revision: Union[str, None] = '21fc479d1ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookings_table_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'tables', ['table_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_table_id_fkey', 'bookings', 'tables', ['table_id'], ['id'])
    # ### end Alembic commands ###
